name:                glados-vm
version:             0.1.0.0
github:              "enzogagg/glados"
license:             BSD-3-Clause
author:              "GLaDOS Team"
maintainer:          "team@example.com"

dependencies:
- base >= 4.14 && < 5
- containers
- bytestring
- binary

executables:
  glados-vm:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - bytestring
    - binary

