name:                glados-vm
version:             0.1.0.0
github:              "enzogagg/glados"
license:             BSD-3-Clause
author:              "GLaDOS Team"
maintainer:          "team@example.com"

dependencies:
- base >= 4.14 && < 5
- containers
- bytestring
- binary
- directory

library:
  source-dirs: src

executables:
  glados-vm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados-vm

tests:
  vm-test:
    main:                Spec.hs
    source-dirs:         ../test/vm/unitary
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados-vm
    - base
    - hspec
    - silently

