(define l (list 1 2 3))
(define c (cons 0 l))
(if (eq? (car l) 1)
    (if (eq? (car (cdr l)) 2)
        (if (null? (list))
            (if (eq? (car c) 0)
                (car (cdr c))
                0)
            0)
        0)
    0)
